Release 1.5.2
Just a re-release due to error below but bumping to avoid file caching.
Error was:
HTTPError: 400 Client Error: Duplicate file upload detected.
for url: https://pypi.python.org/pypi