Fixes exit_maintenance error
Latest bootstrap-cfn break exit_maintenance task with the following error:

```
Traceback (most recent call last):
  File "/Users/filippos/.virtualenvs/advocate-defence-payments-deploy/lib/python2.7/site-packages/fabric/main.py", line 745, in main
    *args, **kwargs
  File "/Users/filippos/.virtualenvs/advocate-defence-payments-deploy/lib/python2.7/site-packages/fabric/tasks.py", line 427, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/Users/filippos/.virtualenvs/advocate-defence-payments-deploy/lib/python2.7/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/Users/filippos/.virtualenvs/advocate-defence-payments-deploy/lib/python2.7/site-packages/bootstrap_cfn/fab_tasks.py", line 260, in exit_maintenance
    for x in elb_conn.cfn.get_stack_load_balancers(stack_name)])
AttributeError: 'dict' object has no attribute 'logical_resource_id'
```
Reason is because the attribute now is now called LogicalResourceId
and PhysicalResourceId.