Readd elb permissions to ec2 host for aws-formula
Highstating with aws-formula currently produces this error:

```
[ERROR   ] 403 Forbidden
[ERROR   ] <ErrorResponse xmlns="http://elasticloadbalancing.amazonaws.com/doc/2012-06-01/">
  <Error>
    <Type>Sender</Type>
    <Code>AccessDenied</Code>
    <Message>User: arn:aws:sts::NNNNNNNNNNN:assumed-role/.. is not authorized to perform: elasticloadbalancing:DescribeLoadBalancers</Message>
  </Error>
  <RequestId>ffa4bb0f-420e-11e6-a63b-e3fe5e66e8f5</RequestId>
</ErrorResponse>

[ERROR   ] Error getting ELB names: BotoServerError: 403 Forbidden
<ErrorResponse xmlns="http://elasticloadbalancing.amazonaws.com/doc/2012-06-01/">
  <Error>
    <Type>Sender</Type>
    <Code>AccessDenied</Code>
    <Message>User: arn:aws:sts::NNNNNNNNNNN:assumed-role/.. is not authorized to perform: elasticloadbalancing:DescribeLoadBalancers</Message>
  </Error>
  <RequestId>ffa4bb0f-420e-11e6-a63b-e3fe5e66e8f5</RequestId>
</ErrorResponse>
Traceback (most recent call last):
  File "a", line 43, in get_elb_lbs
    all_lbs = [lb for lb in elb_connection.get_all_load_balancers()
  File "/usr/local/lib/python2.7/dist-packages/boto/ec2/elb/__init__.py", line 135, in get_all_load_balancers
    [('member', LoadBalancer)])
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1186, in get_list
    raise self.ResponseError(response.status, response.reason, body)
BotoServerError: BotoServerError: 403 Forbidden
<ErrorResponse xmlns="http://elasticloadbalancing.amazonaws.com/doc/2012-06-01/">
  <Error>
    <Type>Sender</Type>
    <Code>AccessDenied</Code>
    <Message>User: arn:aws:sts::NNNNNNNNNNN:assumed-role/.. is not authorized to perform: elasticloadbalancing:DescribeLoadBalancers</Message>
  </Error>
  <RequestId>ffa4bb0f-420e-11e6-a63b-e3fe5e66e8f5</RequestId>
</ErrorResponse>

{'custom_grain_error': True}
```

This is due to:
https://github.com/ministryofjustice/bootstrap-cfn/commit/06a185a04432e5fc95f159535303343affadaa2b

Adding access to just its own load balancer is not enough, because to query
(eg: Describe) it you have to already know and supply the resource name.
If no name is specified then a `*` is implied.